# Generated by Django 5.2.13 on 2026-04-14 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('company_overview', '회사소개서'), ('sales_proposal', '영업제안서'), ('government_proposal', '정부과제문서'), ('demo_report', '실증보고서'), ('meeting_note', '회의록')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, upload_to='document_templates/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('block_type', models.CharField(choices=[('text', '텍스트'), ('slide', '슬라이드'), ('table', '표'), ('image', '이미지')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('approval_status', models.CharField(choices=[('draft', '초안'), ('approved', '승인'), ('archived', '보관')], default='draft', max_length=20)),
                ('certifications', models.ManyToManyField(blank=True, related_name='document_blocks', to='knowledge.certification')),
                ('patents', models.ManyToManyField(blank=True, related_name='document_blocks', to='knowledge.patent')),
                ('references', models.ManyToManyField(blank=True, related_name='document_blocks', to='knowledge.reference')),
                ('technologies', models.ManyToManyField(blank=True, related_name='document_blocks', to='knowledge.technology')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', '초안'), ('review', '검토중'), ('approved', '승인완료'), ('exported', '배포완료')], default='draft', max_length=20)),
                ('assembled_content', models.JSONField(blank=True, default=dict)),
                ('exported_file', models.FileField(blank=True, upload_to='generated_documents/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='crm.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='crm.opportunity')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', '대기'), ('running', '실행중'), ('failed', '실패'), ('completed', '완료')], default='queued', max_length=20)),
                ('output_format', models.CharField(default='pptx', max_length=20)),
                ('execution_log', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.generateddocument')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
