# Generated by Django 5.2.13 on 2026-04-14 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('company_overview', '회사소개서'), ('sales_proposal', '영업 제안서'), ('government_proposal', '정부과제 문서'), ('demo_report', '실증 보고서'), ('meeting_note', '회의록')], max_length=40),
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('company_overview', '회사소개서'), ('sales_proposal', '영업 제안서'), ('government_proposal', '정부과제 문서'), ('demo_report', '실증 보고서'), ('meeting_note', '회의록')], max_length=40)),
                ('file_format', models.CharField(choices=[('pptx', 'PPT'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('docx', 'Word'), ('etc', '기타')], default='pdf', max_length=20)),
                ('source_file', models.FileField(upload_to='reference_documents/')),
                ('summary', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='예: company,overview,solution', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_documents', to='crm.company')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_documents', to='crm.opportunity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reference_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
