# Generated by Django 5.2.13 on 2026-04-14 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documenttemplate_template_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_round', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('applied', 'Applied')], default='requested', max_length=20)),
                ('general_feedback', models.TextField(blank=True)),
                ('text_feedback', models.TextField(blank=True)),
                ('image_feedback', models.TextField(blank=True)),
                ('block_feedback', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revision_requests', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='documents.generateddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevisionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.FileField(upload_to='document_revision_assets/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('revision_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='documents.documentrevisionrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
