# Generated by Django 5.2.13 on 2026-04-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentrevisionrequest_documentrevisionasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('source_event', models.CharField(choices=[('initial_generation', 'Initial Generation'), ('revision_regeneration', 'Revision Regeneration'), ('manual_regeneration', 'Manual Regeneration')], max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('generation_request', models.TextField(blank=True)),
                ('snapshot_payload', models.JSONField(blank=True, default=dict)),
                ('rendered_html', models.TextField(blank=True)),
                ('sync_status', models.CharField(choices=[('pending_setup', 'Pending Setup'), ('committed_local', 'Committed Locally'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending_setup', max_length=30)),
                ('sync_message', models.TextField(blank=True)),
                ('sync_commit_hash', models.CharField(blank=True, max_length=80)),
                ('sync_repo_path', models.CharField(blank=True, max_length=500)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_snapshots', to='documents.generateddocument')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_snapshot')],
            },
        ),
    ]
